version: '2.2'
services:
  web:
    build: .
    ports:
      - "18395:5000"
    cpus: 0.2
    mem_limit: 128M
    restart: on-failure
  redis:
    image: "redis:alpine"
    cpus: 0.
    mem_limit: 128M
    restart: on-failure